"""slate — Sunday job: aggregate discovery, cannibalize, rank, emit slate.

Reads candidates from all four discovery extractors, drops critical/high
cannibalization, ranks the survivors, and produces the top-12 slate. Each
proposal carries a working title, a one-line angle, and three H2 outline
bullets — about 50 LLM tokens per proposal (intentionally cheap; the
expensive prose generation runs on Wednesday for only the 7 Nikki approves).

The slate is written to data/runs/_title-slates/<week>.json AND posted to
ClickUp as a parent task with one subtask per proposal.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Final

from .cannibalization import ProposedTopic, evaluate
from .discover import SOURCE_WEIGHTS, Candidate
from .inventory import Inventory

SLATE_TARGET_COUNT: Final[int] = 12
SLATE_DIR: Final[Path] = Path(__file__).resolve().parents[1] / "data" / "runs" / "_title-slates"


@dataclass(frozen=True)
class SlateProposal:
    """One row of the title slate that lands in ClickUp for Nikki."""

    focus_keyword: str
    working_title: str
    one_line_angle: str
    outline_bullets: list[str]
    slug: str
    audience: str
    category_id: int
    intent: str
    target_date: str

    discovery_source: str
    discovery_id: str
    discovery_evidence: dict[str, Any] = field(default_factory=dict)

    cannibalization_severity: str = "clear"
    cannibalization_rationale: str = ""
    matched_post_url: str | None = None
    score: float = 0.0


@dataclass(frozen=True)
class Slate:
    week: str
    proposals: list[SlateProposal]
    discovery_summary: dict[str, Any]


# ---------------------------------------------------------------------------
# Aggregate / rank / build
# ---------------------------------------------------------------------------


def aggregate(*candidate_lists: list[Candidate]) -> list[Candidate]:
    """Concatenate candidates from multiple sources, dedupe by focus_keyword."""
    seen: set[str] = set()
    out: list[Candidate] = []
    for lst in candidate_lists:
        for cand in lst:
            key = cand.focus_keyword.strip().lower()
            if key in seen:
                continue
            seen.add(key)
            out.append(cand)
    return out


def filter_by_cannibalization(
    candidates: list[Candidate],
    inventory: Inventory,
) -> tuple[list[Candidate], list[tuple[Candidate, str, str]]]:
    """Drop critical/high; keep clear/low/medium with their verdict.

    Returns (survivors, dropped) where dropped is [(cand, severity, rationale), ...]
    """
    survivors: list[tuple[Candidate, str, str]] = []
    dropped: list[tuple[Candidate, str, str]] = []
    for cand in candidates:
        topic = ProposedTopic(
            slug=_slug_from_focus_keyword(cand.focus_keyword),
            title=cand.suggested_title_seed,
            focus_keyword=cand.focus_keyword,
            category_id=cand.category_id,
            audience=cand.audience,  # type: ignore[arg-type]
        )
        verdict = evaluate(topic, inventory)
        if verdict.severity in ("critical", "high"):
            dropped.append((cand, verdict.severity, verdict.rationale))
        else:
            survivors.append((cand, verdict.severity, verdict.rationale))
    # Repackage survivors so the cannibalization metadata is available later
    return [s[0] for s in survivors], dropped + [(s[0], s[1], s[2]) for s in survivors]  # noqa


def rank_candidates(candidates: list[Candidate]) -> list[Candidate]:
    """Sort candidates by source-weighted score, descending."""
    def weighted(c: Candidate) -> float:
        return c.score * SOURCE_WEIGHTS.get(c.discovery_source, 1.0)
    return sorted(candidates, key=weighted, reverse=True)


def build_proposal(
    cand: Candidate,
    *,
    cannibalization_severity: str,
    cannibalization_rationale: str,
    target_date: str,
    title: str | None = None,
    angle: str | None = None,
    outline: list[str] | None = None,
) -> SlateProposal:
    """Wrap a Candidate in a SlateProposal.

    `title`, `angle`, `outline` are normally generated by Claude in the
    Sunday job. If omitted, sensible deterministic defaults are produced
    so the slate JSON is well-formed even before the agent runs.
    """
    seed = cand.suggested_title_seed.strip()
    return SlateProposal(
        focus_keyword=cand.focus_keyword,
        working_title=title or seed,
        one_line_angle=angle or _default_angle(cand),
        outline_bullets=outline or _default_outline(cand),
        slug=_slug_from_focus_keyword(cand.focus_keyword),
        audience=cand.audience,
        category_id=cand.category_id,
        intent=cand.intent,
        target_date=target_date,
        discovery_source=cand.discovery_source,
        discovery_id=cand.discovery_id,
        discovery_evidence=dict(cand.discovery_evidence),
        cannibalization_severity=cannibalization_severity,
        cannibalization_rationale=cannibalization_rationale,
        score=cand.score,
    )


def build_slate(
    *,
    week: str,
    candidates: list[Candidate],
    inventory: Inventory,
    target_count: int = SLATE_TARGET_COUNT,
    target_dates: list[str] | None = None,
    titles_by_focus_kw: dict[str, dict[str, Any]] | None = None,
) -> Slate:
    """End-to-end slate build.

    `titles_by_focus_kw` (optional) lets the caller inject Claude-generated
    title/angle/outline per candidate. Shape:
      {focus_keyword: {"title": "...", "angle": "...", "outline": [...]}}
    """
    inventory.assert_fresh()
    inventory.assert_complete()

    deduped = aggregate(candidates)
    survivors_with_meta: list[tuple[Candidate, str, str]] = []

    for cand in deduped:
        topic = ProposedTopic(
            slug=_slug_from_focus_keyword(cand.focus_keyword),
            title=cand.suggested_title_seed,
            focus_keyword=cand.focus_keyword,
            category_id=cand.category_id,
            audience=cand.audience,  # type: ignore[arg-type]
        )
        verdict = evaluate(topic, inventory)
        if verdict.severity in ("critical", "high"):
            continue
        survivors_with_meta.append((cand, verdict.severity, verdict.rationale))

    survivors_with_meta.sort(
        key=lambda t: t[0].score * SOURCE_WEIGHTS.get(t[0].discovery_source, 1.0),
        reverse=True,
    )
    top = survivors_with_meta[:target_count]

    if target_dates is None:
        target_dates = _default_target_dates(week, count=len(top))

    titles_by_focus_kw = titles_by_focus_kw or {}

    proposals = []
    for i, (cand, sev, rationale) in enumerate(top):
        meta = titles_by_focus_kw.get(cand.focus_keyword, {})
        proposals.append(
            build_proposal(
                cand,
                cannibalization_severity=sev,
                cannibalization_rationale=rationale,
                target_date=target_dates[i] if i < len(target_dates) else "",
                title=meta.get("title"),
                angle=meta.get("angle"),
                outline=meta.get("outline"),
            )
        )

    by_source: dict[str, int] = {}
    for p in proposals:
        by_source[p.discovery_source] = by_source.get(p.discovery_source, 0) + 1
    summary = {"by_source": by_source, "total_emitted": len(proposals)}

    return Slate(week=week, proposals=proposals, discovery_summary=summary)


# ---------------------------------------------------------------------------
# Persistence
# ---------------------------------------------------------------------------


def write_slate(slate: Slate, *, dir_: Path = SLATE_DIR) -> Path:
    dir_.mkdir(parents=True, exist_ok=True)
    path = dir_ / f"{slate.week}.json"
    payload = {
        "week": slate.week,
        "proposals": [asdict(p) for p in slate.proposals],
        "discovery_summary": slate.discovery_summary,
    }
    with path.open("w", encoding="utf-8") as fh:
        json.dump(payload, fh, ensure_ascii=False, indent=2)
    return path


def load_slate(week: str, *, dir_: Path = SLATE_DIR) -> Slate:
    path = dir_ / f"{week}.json"
    with path.open(encoding="utf-8") as fh:
        data = json.load(fh)
    proposals = [SlateProposal(**p) for p in data.get("proposals", [])]
    return Slate(
        week=data["week"],
        proposals=proposals,
        discovery_summary=data.get("discovery_summary", {}),
    )


# ---------------------------------------------------------------------------
# Internals
# ---------------------------------------------------------------------------


def _slug_from_focus_keyword(focus_keyword: str) -> str:
    import re
    s = focus_keyword.lower().strip()
    s = re.sub(r"[^a-z0-9\s\-]", "", s)
    s = re.sub(r"[\s_]+", "-", s)
    s = re.sub(r"-+", "-", s).strip("-")
    return s[:80]


def _default_angle(cand: Candidate) -> str:
    sources = {
        "gsc_striking_distance": "Real demand we already partially rank for; one clean post away from page 1.",
        "ahrefs_competitor_gap": "Competitor ranks for this; we don't. Owning it shifts SoV in the SERP.",
        "searchable_prompt": "AI engines cite competitors here; a focused post earns First Movers a citation.",
        "searchable_competitor_topic": "Topic where our share of voice is below threshold across AI engines.",
        "ga4_high_traffic_gap": "Companion post to feed an already-rising page; creates a topical cluster.",
    }
    return sources.get(cand.discovery_source, cand.rationale[:140])


def _default_outline(cand: Candidate) -> list[str]:
    """Three generic H2-level beats. The Sunday agent overrides these with
    Claude-generated outline bullets per topic.
    """
    return [
        f"Why {cand.focus_keyword} matters now (the operator-level reason)",
        f"How leading teams approach {cand.focus_keyword} (3 patterns from the field)",
        f"How First Movers helps with {cand.focus_keyword} (audience-routed CTA)",
    ]


def _default_target_dates(week: str, *, count: int) -> list[str]:
    """Spread `count` target publish dates across the week's Mon-Sun."""
    try:
        year_str, w = week.split("-W")
        year = int(year_str)
        week_no = int(w)
    except (ValueError, AttributeError):
        return [""] * count
    monday = datetime.fromisocalendar(year, week_no, 1)
    return [(monday + timedelta(days=i % 7)).strftime("%Y-%m-%d") for i in range(count)]


# ---------------------------------------------------------------------------
# CLI — `python -m tools.slate --help`
# ---------------------------------------------------------------------------


def _main(argv: list[str] | None = None) -> int:
    """Build a slate from a candidates bundle.

    The agent collects raw MCP responses, runs each through its discover/*
    extractor, concatenates the resulting Candidate lists, and dumps them
    to a single JSON file with this shape:

        {
          "candidates": [
            {"focus_keyword": "...", "suggested_title_seed": "...", ...},
            ...
          ],
          "titles_by_focus_kw": {            # optional, agent-generated
            "<focus_kw>": {"title": "...", "angle": "...", "outline": [...]}
          }
        }

    Then runs:

        python -m tools.slate --week 2026-W22 --candidates path/to/bundle.json --emit

    `--emit` writes the slate JSON to disk. `--dry-run` (default) prints
    the slate to stdout for inspection.
    """
    import argparse
    from .discover import Candidate
    from .inventory import load as load_inventory

    parser = argparse.ArgumentParser(prog="tools.slate")
    parser.add_argument("--week", required=True, help="Week tag e.g. 2026-W22")
    parser.add_argument("--candidates", required=True,
                        help="Path to JSON bundle of Candidate dicts")
    parser.add_argument("--target-count", type=int, default=SLATE_TARGET_COUNT)
    parser.add_argument("--emit", action="store_true",
                        help="Write the slate to data/runs/_title-slates/")
    args = parser.parse_args(argv)

    inv = load_inventory()
    inv.assert_fresh()
    inv.assert_complete()

    with Path(args.candidates).open(encoding="utf-8") as fh:
        bundle = json.load(fh)

    cands = [Candidate(**c) for c in bundle.get("candidates", [])]
    titles = bundle.get("titles_by_focus_kw") or None

    slate = build_slate(
        week=args.week,
        candidates=cands,
        inventory=inv,
        target_count=args.target_count,
        titles_by_focus_kw=titles,
    )

    if args.emit:
        path = write_slate(slate)
        print(f"wrote {path}  ({len(slate.proposals)} proposals)")
    else:
        print(json.dumps(
            {
                "week": slate.week,
                "summary": slate.discovery_summary,
                "proposals": [asdict(p) for p in slate.proposals],
            },
            ensure_ascii=False,
            indent=2,
        ))
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
